apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-dev
  namespace: argocd
  labels:
    app.kubernetes.io/name: app-of-apps
    app.kubernetes.io/instance: dev
    app.kubernetes.io/managed-by: argocd
    environment: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/rezaDevOps/argocd-terraform-eks.git
    targetRevision: HEAD
    path: gitops-repo/apps
    helm:
      valueFiles:
        - ../environments/dev/values.yaml
      values: |
        global:
          environment: dev
          repository:
            url: "https://github.com/rezaDevOps/argocd-terraform-eks.git"
          destination:
            server: "https://kubernetes.default.svc"
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
            syncOptions:
              - CreateNamespace=true
              - PrunePropagationPolicy=foreground
              - PruneLast=true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
